# Generated by Django 3.2.7 on 2021-11-12 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.events', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='table_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер стола'),
        ),
        migrations.AlterField(
            model_name='visits',
            name='payment_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена к оплате'),
        ),
        migrations.AlterField(
            model_name='visits',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.reservations', verbose_name='Бронирование'),
        ),
        migrations.AlterField(
            model_name='visits',
            name='time_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания посещения'),
        ),
    ]
